name: Enterprise CI

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:

  build:
    name: Build Security Quality Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      # -----------------------------
      # Checkout Repository
      # -----------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4


      # -----------------------------
      # Setup Node.js
      # -----------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm


      # -----------------------------
      # Install Dependencies
      # -----------------------------
      - name: Install Dependencies
        run: npm ci


      # -----------------------------
      # Verify Repository
      # -----------------------------
      - name: Verify Repository Files
        run: |
          ls -la
          pwd


      # -----------------------------
      # Application Validation
      # -----------------------------
      - name: Run Application
        run: |
          node app.js &
          sleep 10


      # -----------------------------
      # Docker Build
      # -----------------------------
      - name: Build Docker Image
        run: docker build -t banking-api:latest .


      # -----------------------------
      # Trivy Filesystem Scan
      # -----------------------------
      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          format: table
          exit-code: 1


      # -----------------------------
      # Trivy Docker Image Scan
      # -----------------------------
      - name: Trivy Docker Image Scan
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: banking-api:latest
          severity: CRITICAL,HIGH
          format: table
          exit-code: 1


      # -----------------------------
      # SonarQube Analysis
      # -----------------------------
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}